version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
      - DB_NAME=${db_name}
    command: air
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 88:8888
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    command: npm run serve
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:${db_port}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_USER=${db_user}
      - POSTGRES_DB=${db_name}
volumes:
  db-data:
  node_modules: